### ISSUE TITLE
Peer to Peer (12/23/2021)

### ISSUE THREAD

**Issue by RayhanTabase** [AnselemOdims/MazeFlix#80]
The project looks amazing 🤩🤩🤩 , nothing else to say other than a great job done. Everything looks good, keep up the good work ⭐⭐⭐⭐⭐.

**Comment by charlesgobina** [comment]
Great job on implementing the project 🚀  . 
## Commendations
* DRY code ✔️ 
* Modular Code ✔️

**Comment by AnselemOdims** [comment]
Thanks for the feedback guys.
